# function available minimum required
availableFunctions:
  - plotVar
integratedFunctions:
# web client integrated function configuration
  # advanced
  plotVar:
    description : | 
      An app that help you to compare two variables
    label: "Compare two variables"
    type: graphic
    graphicType: plotly
    linkedFunctions:
      getDF:
        label: "See compute data"
        name: getDF
        type: grid
        parameters:
          - startDate
          - endDate
          - varURI
          - smoothing
          - token
          - wsUrl
    formParameters: # form parameters
      startDate:
        label: "Start date of data"
        type: date
        format: yyyy-mm-dd
        dateValue: Y-m-d
      endDate:
        label: "End date of data"
        type: date
        format: yyyy-mm-dd
        dateValue: Y-m-d
      varURI:
        label: "Variables"
        type: list
        maxSelectedItem: 2
        RfunctionValues: variableList
        required: true
      smoothing:
        label: "Smoothing"
        type: boolean
        defaultValue: false
      token:
        type: string
        visibility: hidden
        required: true
      wsUrl:
        type: string
        visibility: hidden
        required: true
  